ITEM_SUPER_CATEGORY_MEN = "Men"
ITEM_SUPER_CATEGORY_WOMEN = "Women"
ITEM_SUPER_CATEGORY_BOYS = "Boys"
ITEM_SUPER_CATEGORY_GIRLS = "Girls"
ITEM_SUPER_CATEGORY_ADULT = "Adult"
ITEM_SUPER_CATEGORY_CHILDREN = "Children"
ITEM_SUPER_CATEGORY_ALL = "All"


ITEM_SUB_CATEGORY_SHIRTS = "Shirts"
ITEM_SUB_CATEGORY_PANTS = "Pants"
ITEM_SUB_CATEGORY_SHOES = "Shoes"
ITEM_SUB_CATEGORY_ACCESSORIES = "Accessories"
ITEM_SUB_CATEGORY_MISC = "Misc"


