# Generated by Django 3.0.6 on 2020-05-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
